name: Eco
version: 1.0
author: Chipscrash/Predictionking
main: com.chipscrash.main.Main
api-version: 1.16
commands:
  heal:
    description: Full healthbar and Foodbar
    usage: /heal
  register:
    description: Register user
    usage: /register <Password>
  login:
    description: Login user
    usage: /login <Password>
  feed:
    description: Full Foodbar
    usage: /feed
  god:
    description: Become god
    usage: /god
